### ISSUE TITLE
Merry Christmas

### ISSUE THREAD

**Issue by patrickmcm** [NotDSF/LuauDissasembler#1]
Q2Z0dHcgT250aml1Y3JpLCBZQyBjZiBwbCB5amlvcHR5IHFwdCByIHZqcXUu

- peanut

**Comment by NotDSF** [comment]
Cfttw Ontjiucri, YC cf pl yjiopty qpt r vjqu.

**Comment by NotDSF** [comment]
Merry Christmas, DM me to redeem your gift.

**Comment by Peanut1120** [comment]
this was such a hard issue to solve
